// Generated by sync_stratrules.py -- GDD §4.9, §4.11 row 9.
//
// The vendored rules module. Its SOURCES carry zero engine dependencies -- no engine
// headers, no UObject, no third-party includes, pure C++17 in `namespace strat` --
// which is what T-INT-04 asserts by compiling them standalone, outside UBT entirely.
// This file is the UBT wrapper around them. It is tracked in the crew repo at
// ue_module/StratRules.Build.cs and vendored from the object store like the sources,
// so T-INT-01 hash-matches it against that commit rather than exempting it.
//
// `Core` is the minimum a UBT module declares. Nothing in Source/StratRules/*.h or
// *.good.cpp includes it; adding a dependency here would not change that, but it
// would make the claim harder to check, so the list stays at one.

using UnrealBuildTool;

public class StratRules : ModuleRules
{
	public StratRules(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.NoPCHs;
		bUseUnity = false;

		PublicDependencyModuleNames.AddRange(new string[] { "Core" });
		PrivateDependencyModuleNames.AddRange(new string[] { });
		PublicIncludePaths.AddRange(new string[] { "StratRules" });
	}
}
