// Test Engineer's gate for §4.11 row 10, PART (b) — headless replayer + §4.10's
// canonical state hash.
//
// WHAT THIS SUITE CLOSES, and why that is four IDs and not five. Part (b) runs
// T-SAVE-01/02/03/05/06. `T-SAVE-06` asserts the hash is identical across the
// HEADLESS and IN-ENGINE builds; it is marked † in §4.11 and asserted jointly with
// T-INT-02, which replays IN-ENGINE -- so it cannot close in a headless build, and
// it is printed by name at the end rather than folded into the tally. The reason
// this comment used to give -- that T-INT-02 needed a vendored replayer a ruling
// deferred -- is spent, Save and Replay having been vendored at f5fdb69. The four
// this suite closes are T-SAVE-01, 02, 03 and 05.
//
// THE LOG CARRIES THE COMPLETE §4.9 COMMAND SET. Q29's conservative reading closes
// an acceptance ID only when its whole written fixture set ran, and §4.11 puts
// closure on rows 4-5 completing the command set and row 6 completing T-SAVE-02's
// determinism composition. All three have landed, so the canonical log below
// exercises `Move`, `Attack`, `Build`, `Capture` and `EndTurn`, and a segment of it
// is generated by row 6's AI rather than hand-written -- which is what puts T-AI-06
// inside T-SAVE-02's composition instead of beside it.
//
// THE CHECK RECOMPUTES; IT DOES NOT DELEGATE. The serialisation check below builds
// §4.10's byte stream independently, field by field, from the fixture's own values
// -- it never asks `canonicalStateBytes` what it thinks the order is. A check that
// compared two calls to the implementation would agree with any field order,
// correct or not, and the field order IS the invariant here.
//
// THE HAND-BUILT FIXTURE TABLES ARE BUILT HERE, not loaded from data/. Loading the
// shipped CSVs would make every check that turns on a stat depend on row 2's files,
// and every number those checks turn on would then be a value nobody in this file
// chose. Every check from GATE-REPLAY-SETUP through T-SAVE-05 runs on those tables.
//
// GATE-REPLAY-FIXTURE IS THE ONE EXCEPTION, and it is an exception on purpose. It
// asserts over `data/parity_fixture.save`, the committed §4.10 file T-INT-02 replays
// IN-ENGINE, and the UE side reads `data/units.csv`, `data/terrain.csv` and
// `data/ferrum_crossing.json` -- the bytes `sync_stratdata.py` vendors. A parity
// fixture seeded from tables nobody ships would compare two different games, so this
// one check loads the real files and turns on no number of its own: it asserts a
// replay succeeds, that a carried digest equals a recomputed one, and that re-emitting
// reproduces the committed bytes. Both worlds seed through `seedFromScenario`, the
// only Scenario -> GameState mapping in the project.
#include "Ai.h"
#include "Data.h"
#include "Hex.h"
#include "Replay.h"
#include "Save.h"
#include "Scenario.h"

#include <algorithm>
#include <cstdio>
#include <string>
#include <vector>

using namespace strat;

static int g_total = 0;
static int g_fail  = 0;

static void check(const char* name, bool cond) {
    ++g_total;
    if (cond) { std::printf("PASS  %s\n", name); }
    else      { std::printf("FAIL  %s\n", name); ++g_fail; }
}

// ---------------------------------------------------------------------------
// Fixture. A 5x3 board: plains, with a factory per SIDE -- (0,2) side 0's, (4,2)
// side 1's -- and one neutral town at (2,1) to capture.
//
// THE FACTORY COUNT IS LOAD-BEARING, not scenery. §2.8's domination backstop
// (T-TURN-03) ends a match the moment one side holds EVERY factory, and row 5 checks
// it at `beginTurn`. A fixture with a single factory is therefore over before its
// first command: the match ends inside `openTurn` and every later command is refused
// "no match is running". Two factories, one per side, is the smallest board on which
// a turn can actually be played.
// ---------------------------------------------------------------------------
static std::vector<TerrainDef> fixtureTerrain() {
    std::vector<TerrainDef> t(3);
    t[0].id = "Plains";  t[0].moveCost = 1; t[0].defensePct = 0; t[0].passLand = true;
    t[1].id = "Factory"; t[1].moveCost = 1; t[1].defensePct = 0; t[1].passLand = true;
    t[1].capturable = true; t[1].incomeFame = 100; t[1].isSpawnPoint = true;
    t[2].id = "Town";    t[2].moveCost = 1; t[2].defensePct = 10; t[2].passLand = true;
    t[2].capturable = true; t[2].incomeFame = 25;
    return t;
}

static std::vector<UnitDef> fixtureUnits() {
    std::vector<UnitDef> u(2);
    u[0].id = "Infantry"; u[0].hpMax = 10; u[0].move = 3; u[0].atk = 4; u[0].def = 2;
    u[0].rangeMin = 1; u[0].rangeMax = 1; u[0].costFame = 100;
    u[0].type = UnitType::Infantry; u[0].canCapture = true;
    u[1].id = "Tank";     u[1].hpMax = 20; u[1].move = 3; u[1].atk = 8; u[1].def = 5;
    u[1].rangeMin = 1; u[1].rangeMax = 1; u[1].costFame = 200;
    u[1].type = UnitType::Tank;     u[1].canCapture = false;
    return u;
}

static GameUnit mkUnit(int id, int side, int defIndex, int col, int row, int hp) {
    GameUnit u;
    u.id = id; u.side = side; u.defIndex = defIndex;
    u.hex = offsetToAxial(col, row);
    u.placement = u.hex;
    u.hp = hp;
    return u;
}

static GameState fixtureState(const std::vector<UnitDef>& ud,
                              const std::vector<TerrainDef>& td) {
    GameState g;
    g.bounds.cols = 5; g.bounds.rows = 3;
    g.terrain.assign(15, 0);
    g.terrain[2 * 5 + 0] = 1;                 // Factory at (0,2), side 0's
    g.terrain[2 * 5 + 4] = 1;                 // Factory at (4,2), side 1's
    g.terrain[1 * 5 + 2] = 2;                 // Town    at (2,1), neutral

    g.units.push_back(mkUnit(1, 0, 0, 1, 1, 10));   // side 0 Infantry
    g.units.push_back(mkUnit(2, 0, 1, 0, 0, 20));   // side 0 Tank  (the flag)
    g.units.push_back(mkUnit(3, 1, 0, 4, 1, 10));   // side 1 Infantry
    g.nextUnitId = 4;
    g.flagUnit[0] = 2;
    g.flagUnit[1] = -1;                             // side 1 designates none

    initSide(g.economy, 0, 400);
    initSide(g.economy, 1, 400);
    Objective f0; f0.hex = offsetToAxial(0, 2); f0.owner = 0; f0.terrainIndex = 1;
    Objective f1; f1.hex = offsetToAxial(4, 2); f1.owner = 1; f1.terrainIndex = 1;
    Objective tn; tn.hex = offsetToAxial(2, 1); tn.owner = OWNER_NEUTRAL;
    tn.terrainIndex = 2;
    g.economy.objectives.push_back(f0);
    g.economy.objectives.push_back(f1);
    g.economy.objectives.push_back(tn);
    g.economy.captureTurns = 1;

    std::string err;
    initMatch(g.turn, 0, 20, err);
    // initMatch leaves the phase TurnPending; the first turn is opened the same way
    // every later one is, so the initial state here is a state a real match reaches.
    RulesTables t;
    t.units = &ud;
    t.terrain = &td;
    openTurn(g, t);
    return g;
}

static SaveCommand cmd(SaveCommandKind k, int turn, int side, int unitId,
                       int col, int row, bool hasHex, bool hasUnit) {
    SaveCommand c;
    c.turn = turn; c.side = side; c.kind = k;
    c.unitId = unitId;
    if (hasHex) c.hex = offsetToAxial(col, row);
    c.hasHex = hasHex; c.hasUnit = hasUnit;
    return c;
}

// The canonical log: all five §4.9 commands, side 0's turn.
//   Move    #1 (1,1) -> (2,1)   Infantry onto the neutral town
//   Move    #2 (0,0) -> (1,0)   the Tank, BEFORE the build -- a unit the build
//                               spawns can box a route in, and Q3's conservative
//                               reading makes any occupied hex block pathing
//   Capture side 0              the tick that takes the town (captureTurns == 1)
//   Build   Infantry at (0,2)   side 0's own factory, unoccupied
//   EndTurn
static std::vector<SaveCommand> canonicalLog() {
    std::vector<SaveCommand> log;
    log.push_back(cmd(SaveCommandKind::Move,    1, 0, 1, 2, 1, true,  true));
    log.push_back(cmd(SaveCommandKind::Move,    1, 0, 2, 1, 0, true,  true));
    log.push_back(cmd(SaveCommandKind::Capture, 1, 0, 0, 0, 0, false, false));
    log.push_back(cmd(SaveCommandKind::Build,   1, 0, 0, 0, 2, true,  true));
    log.push_back(cmd(SaveCommandKind::EndTurn, 1, 0, 0, 0, 0, false, false));
    return log;
}

// ---------------------------------------------------------------------------
// Row 6's AI, driven against the replayer's own state. Its commands enter the log
// exactly as a player's would -- which is the property row 6's stub claims and the
// reason T-AI-06's determinism composes into T-SAVE-02 rather than sitting beside it.
// ---------------------------------------------------------------------------
static AiState aiViewOf(const GameState& g, const std::vector<UnitDef>& ud,
                        const std::vector<TerrainDef>& td) {
    AiState s;
    s.bounds = g.bounds;
    s.terrain = g.terrain;
    s.unitDefs = ud;
    s.terrainDefs = td;
    s.economy = g.economy;
    s.turn = g.turn;
    s.builtThisTurn = g.turn.builtThisTurn;
    for (const GameUnit& u : g.units) {
        AiUnit a;
        a.id = u.id; a.side = u.side; a.defIndex = u.defIndex; a.hex = u.hex;
        a.hp = u.hp; a.isFlag = isFlagUnit(g, u);
        s.units.push_back(a);
    }
    return s;
}

// Converts one AiCommand into the §4.9 vocabulary the log records. Attack is tagged
// by TARGET HEX (§4.10's `{turn, side}` plus §4.9's `Attack{unit, targetHex}`), so
// the target's id is resolved to its hex here and never stored as an id.
static bool aiCommandToSave(const GameState& g, const AiCommand& a, int turn, int side,
                            SaveCommand& out) {
    out = SaveCommand();
    out.turn = turn; out.side = side;
    switch (a.kind) {
    case AiCommandKind::Move:
        out.kind = SaveCommandKind::Move; out.unitId = a.unitId; out.hex = a.hex;
        out.hasUnit = true; out.hasHex = true; return true;
    case AiCommandKind::Attack: {
        const GameUnit* target = findGameUnit(g, a.targetId);
        if (target == nullptr) return false;
        out.kind = SaveCommandKind::Attack; out.unitId = a.unitId; out.hex = target->hex;
        out.hasUnit = true; out.hasHex = true; return true;
    }
    case AiCommandKind::Build:
        out.kind = SaveCommandKind::Build; out.unitId = a.defIndex; out.hex = a.hex;
        out.hasUnit = true; out.hasHex = true; return true;
    case AiCommandKind::EndTurn:
        out.kind = SaveCommandKind::EndTurn; return true;
    }
    return false;
}

// Plays side 1's turn with row 6's AI, appending every command it emits to `log` and
// applying each to `g`. Bounded, so a misbehaving AI cannot hang the gate.
static void appendAiTurn(GameState& g, std::vector<SaveCommand>& log,
                         const RulesTables& t, const std::vector<UnitDef>& ud,
                         const std::vector<TerrainDef>& td, int side) {
    for (int guard = 0; guard < 32; ++guard) {
        const AiState view = aiViewOf(g, ud, td);
        const AiCommand a = nextCommand(view, side);
        SaveCommand sc;
        if (!aiCommandToSave(g, a, g.turn.turnNumber, side, sc)) break;
        const ReplayResult r = applyCommand(g, sc, t);
        if (!r.ok) break;                 // the AI proposed something the rules refuse
        log.push_back(sc);
        if (a.kind == AiCommandKind::EndTurn) break;
    }
}

// ---------------------------------------------------------------------------
// A save file carrying a log, so the round trip goes through the real §4.10 format
// rather than through a vector handed straight back.
// ---------------------------------------------------------------------------
static Save saveFor(const std::vector<SaveCommand>& log, const std::string& stateHash) {
    Save s;
    s.formatVersion = kFormatVersion;
    s.rulesCommit   = "part-b";
    s.dataHash      = "1122334455667788";
    s.scenarioId    = "replay_fixture";
    s.scenarioHash  = "99aabbccddeeff00";
    s.seed          = 0;
    s.commandLog    = log;
    s.stateHash     = stateHash;
    s.hasResult     = false;
    return s;
}

static SaveHeaderExpectation expectationFor(const Save& s) {
    SaveHeaderExpectation e;
    e.expectedVersion = s.formatVersion;
    e.rulesCommit     = s.rulesCommit;
    e.dataHash        = s.dataHash;
    e.scenarioHash    = s.scenarioHash;
    return e;
}

// ---------------------------------------------------------------------------
// THE PARITY FIXTURE — data/parity_fixture.save, the subject of T-INT-02.
//
// ONE BUILDER, TWO CALLERS. `--emit-fixture` writes what this returns; the
// GATE-REPLAY-FIXTURE check below rebuilds it and compares bytes. A second builder
// for the check would compare an emitter against itself and could not see the
// fixture go stale, which is the only thing that check exists to see.
//
// EVERY INPUT IS A SHIPPED FILE. The tables and the scenario are the ones
// `sync_stratdata.py` vendors into the UE project, and the seed is
// `seedFromScenario` -- the project's only Scenario -> GameState mapping, so the
// engine side cannot reach a different starting state by re-deriving one.
//
// `firstSide` IS 0 HERE AND MUST BE 0 THERE. Replay.h states that no rule in this
// project decides it and that a disagreement between the two callers shows up as a
// hash divergence; that is T-INT-02 doing its job, so the value is written once, in
// a named constant, rather than defaulted twice.
// ---------------------------------------------------------------------------
static const int kParityFirstSide = 0;

// How many turns of row 6's AI the log carries. Bounded so the emitter terminates
// whatever the AI does, and large enough to cross a turn boundary -- a replay that
// skips the start-of-turn moment diverges only AFTER the first boundary (Replay.h),
// so a single-turn log could not catch the defect the fixture exists to catch.
//
// 14 IS SLACK, NOT THE LENGTH OF THE MATCH. On the shipped scenario the match ends
// inside turn 11 -- `turn.running` goes false, tier leaves InProgress and side 0
// wins -- and the loop below stops there, so the emitted log is 64 commands and 14
// is never reached. The bound is deliberately above that number rather than equal
// to it: at a bound equal to the match length, a rule or table change that made the
// game one turn longer would silently emit a TRUNCATED fixture, and every check
// below would still pass on it, because they all compare this builder against
// itself. Slack is what makes truncation impossible rather than merely unlikely.
//
// The consequence of playing to the end, and it is the point: the in-engine replay
// T-INT-02 runs crosses the victory path and the MatchOver transition, not just the
// mid-match moves. Two command kinds are still unexercised and no constant here can
// change that -- `AiCommandKind` is {Build, Move, Attack, EndTurn}, so this producer
// cannot emit a Capture at all, and Build never becomes affordable on this scenario.
// The command surface T-INT-03 asserts over is reached by submitting commands
// in-engine, not by replaying this file.
static const int kParityTurns = 14;

// `rulesCommit` and `dataHash` are §4.10 header strings that Save.h defines as
// CALLER-SUPPLIED and never recomputes -- no module in this repo computes a digest
// over the §4.8 CSVs, so neither is derived here and neither is dressed up as a
// digest. They label the file; `checkHeader` is not what GATE-REPLAY-FIXTURE runs.
static const char* kParityRulesCommit = "parity-fixture";
static const char* kParityDataHash    = "parity-fixture";

static bool readWholeFile(const std::string& path, std::string& out) {
    std::FILE* f = std::fopen(path.c_str(), "rb");
    if (f == nullptr) return false;
    out.clear();
    char buf[4096];
    std::size_t n = 0;
    while ((n = std::fread(buf, 1, sizeof(buf), f)) > 0) out.append(buf, n);
    std::fclose(f);
    return true;
}

static bool writeWholeFile(const std::string& path, const std::string& text) {
    std::FILE* f = std::fopen(path.c_str(), "wb");
    if (f == nullptr) return false;
    const std::size_t n = std::fwrite(text.data(), 1, text.size(), f);
    std::fclose(f);
    return n == text.size();
}

// Loads the shipped tables and scenario. `ud`/`td` are the caller's because
// RulesTables BORROWS them and the borrow must outlive every use.
static bool loadShipped(const std::string& dataDir, std::vector<UnitDef>& ud,
                        std::vector<TerrainDef>& td, Scenario& sc, std::string& err) {
    if (!loadUnits(dataDir + "/units.csv", ud, err)) return false;
    if (!loadTerrain(dataDir + "/terrain.csv", td, err)) return false;
    const ScenarioLoadResult r =
        loadScenario(dataDir + "/ferrum_crossing.json", ud, td, sc);
    if (!r.ok) { err = r.failedId + ": " + r.reason; return false; }
    return true;
}

// Seeds from the shipped scenario, plays `kParityTurns` turns of row 6's AI through
// the replayer's own `applyCommand`, and returns the §4.10 file describing the state
// that reaches. Total and deterministic: same bytes in, same bytes out.
static bool buildParityFixture(const std::vector<UnitDef>& ud,
                               const std::vector<TerrainDef>& td,
                               const Scenario& sc, Save& out, std::string& err) {
    RulesTables t;
    t.units = &ud;
    t.terrain = &td;

    GameState g;
    if (!seedFromScenario(g, sc, t, kParityFirstSide, err)) return false;

    std::vector<SaveCommand> log;
    for (int i = 0; i < kParityTurns; ++i) {
        if (!g.turn.running) break;   // the match ended inside the log; stop cleanly
        appendAiTurn(g, log, t, ud, td, g.turn.activeSide);
    }

    out = Save();
    out.formatVersion = kFormatVersion;
    out.rulesCommit   = kParityRulesCommit;
    out.dataHash      = kParityDataHash;
    out.scenarioId    = sc.scenarioId;
    out.scenarioHash  = scenarioHash(sc);
    out.seed          = 0;
    out.commandLog    = log;
    out.stateHash     = canonicalStateHash(g);

    // DERIVED FROM THE STATE THE LOG REACHES, never hardcoded. The log now plays the
    // match to its end, so `result` is a live field rather than a constant, and a
    // literal here would become a false statement about the file the moment the game
    // got shorter or longer.
    //
    // The predicate is the TIER, not `turn.running`, and it is Balance.good.cpp's --
    // `selfPlaySave` is the other place in this repo that writes this field, and one
    // spelling of "the match produced a result" is what keeps the two files from
    // disagreeing. It is also the stricter test: `running` can be false with the tier
    // still InProgress, and that pairing would render the string "InProgress" into a
    // field §4.10 reserves for an outcome.
    if (g.turn.result.tier != ResultTier::InProgress) {
        out.result    = tierName(g.turn.result.tier);
        out.hasResult = true;
    } else {
        out.result.clear();
        out.hasResult = false;
    }
    return true;
}

// EMIT MODE. Writes the fixture and prints the facts a reviewer needs to check it by
// hand: where it went, which scenario it came from, what state hash it carries, what
// outcome that state records, and how the log breaks down by command kind.
static int emitFixture(const std::string& dataDir, const std::string& path) {
    std::vector<UnitDef>    ud;
    std::vector<TerrainDef> td;
    Scenario sc;
    std::string err;
    if (!loadShipped(dataDir, ud, td, sc, err)) {
        std::printf("EMIT FAILED  shipped data did not load: %s\n", err.c_str());
        return 1;
    }
    Save fixture;
    if (!buildParityFixture(ud, td, sc, fixture, err)) {
        std::printf("EMIT FAILED  %s\n", err.c_str());
        return 1;
    }
    const std::string text = serializeSave(fixture);
    if (!writeWholeFile(path, text)) {
        std::printf("EMIT FAILED  could not write %s\n", path.c_str());
        return 1;
    }
    int kinds[5] = {0, 0, 0, 0, 0};
    for (const SaveCommand& c : fixture.commandLog) ++kinds[static_cast<int>(c.kind)];
    std::printf("wrote      %s  (%d bytes)\n", path.c_str(),
                static_cast<int>(text.size()));
    std::printf("scenario   %s  scenarioHash %s\n", fixture.scenarioId.c_str(),
                fixture.scenarioHash.c_str());
    std::printf("stateHash  %s\n", fixture.stateHash.c_str());
    std::printf("result     %s\n",
                fixture.hasResult ? fixture.result.c_str() : "null (match still running)");
    std::printf("log        %d commands over %d AI turns  "
                "(Move %d, Attack %d, Build %d, Capture %d, EndTurn %d)\n",
                static_cast<int>(fixture.commandLog.size()), kParityTurns,
                kinds[0], kinds[1], kinds[2], kinds[3], kinds[4]);
    return 0;
}

int main(int argc, char** argv) {
    // `--data <dir>` names the §4.8 data directory; a bare positional does the same,
    // which is how the row gate invokes every suite in this repo. `--emit-fixture
    // <path>` writes the parity fixture and runs no check -- an emitter that also
    // graded itself would report a tally for a run that asserted nothing.
    std::string dataDir = "../data";
    std::string emitPath;
    for (int i = 1; i < argc; ++i) {
        const std::string a = argv[i];
        if (a == "--data" && i + 1 < argc)              dataDir = argv[++i];
        else if (a == "--emit-fixture" && i + 1 < argc) emitPath = argv[++i];
        else if (a.rfind("--", 0) != 0)                 dataDir = a;
    }
    if (!emitPath.empty()) return emitFixture(dataDir, emitPath);

    const std::vector<UnitDef>    ud = fixtureUnits();
    const std::vector<TerrainDef> td = fixtureTerrain();
    RulesTables tables;
    tables.units = &ud;
    tables.terrain = &td;

    const GameState initial = fixtureState(ud, td);

    // The full log: side 0's five hand-written commands, then side 1's AI turn.
    std::vector<SaveCommand> fullLog = canonicalLog();
    {
        GameState g = initial;
        const ReplayResult r = replayLog(g, fullLog, tables);
        if (!r.ok) std::printf("SETUP FAILED at %d: %s\n", r.failedIndex, r.reason.c_str());
        appendAiTurn(g, fullLog, tables, ud, td, g.turn.activeSide);
    }

    // ---- GATE-REPLAY-SETUP: the fixture log is the complete §4.9 command set -----
    {
        bool seen[5] = {false, false, false, false, false};
        for (const SaveCommand& c : fullLog) seen[static_cast<int>(c.kind)] = true;
        check("GATE-REPLAY-SETUP complete-command-set",
              seen[0] && seen[1] && seen[2] && seen[3] && seen[4]);
        bool anyAi = fullLog.size() > canonicalLog().size();
        check("GATE-REPLAY-SETUP ai-generated-segment-present", anyAi);
    }

    // ---- GATE-REPLAY-BYTES: §4.10's field order, re-derived independently -------
    // Built from the fixture's own values in §4.10's stated order, never by asking
    // the module. If the module reorders a group or drops a field, this diverges.
    {
        GameState g = initial;
        std::string want;
        auto put = [&want](const char* tag, int v) {
            want += tag; want += ':'; want += std::to_string(v); want += ';';
        };
        put("turn", 1);
        put("side", 0);
        put("fT", 400); put("fC", 0);          // side 0
        put("fT", 400); put("fC", 0);          // side 1
        // objectives, sorted into canonical hex order HERE rather than assumed: the
        // fixture's authoring order is not the hash's order, and the point of this
        // check is that the module sorts rather than emits as stored.
        {
            struct O { Hex h; int owner; };
            std::vector<O> os = {
                {offsetToAxial(0, 2), 0},
                {offsetToAxial(4, 2), 1},
                {offsetToAxial(2, 1), OWNER_NEUTRAL},
            };
            std::stable_sort(os.begin(), os.end(), [](const O& a, const O& b) {
                if (!hexEqual(a.h, b.h)) return hexLess(a.h, b.h);
                return a.owner < b.owner;
            });
            for (const O& o : os) { put("oq", o.h.q); put("or", o.h.r); put("ow", o.owner); }
        }
        // units, sorted into canonical hex order here for the same reason
        {
            struct U { Hex h; int id, side, hp, flag; };
            std::vector<U> us = {
                {offsetToAxial(1, 1), 1, 0, 10, 0},
                {offsetToAxial(0, 0), 2, 0, 20, 1},
                {offsetToAxial(4, 1), 3, 1, 10, 0},
            };
            std::stable_sort(us.begin(), us.end(), [](const U& a, const U& b) {
                if (!hexEqual(a.h, b.h)) return hexLess(a.h, b.h);
                return a.id < b.id;
            });
            for (const U& u : us) {
                put("ui", u.id); put("us", u.side);
                put("uq", u.h.q); put("ur", u.h.r);
                put("uh", u.hp);  put("uf", u.flag);
                put("um", 0);     put("ua", 0);
            }
        }
        // no captures, no builds this turn, no pending builds on the initial state
        check("GATE-REPLAY-BYTES canonical-serialisation-field-order",
              canonicalStateBytes(g) == want);
    }

    // ---- GATE-REPLAY-ORDER: the digest does not depend on storage order ---------
    {
        GameState a = initial;
        GameState b = initial;
        std::reverse(b.units.begin(), b.units.end());
        std::reverse(b.economy.objectives.begin(), b.economy.objectives.end());
        check("GATE-REPLAY-ORDER storage-order-does-not-leak",
              canonicalStateHash(a) == canonicalStateHash(b));
    }

    // ---- GATE-REPLAY-FLAGS: the two turn flags are hashed ----------------------
    // A save is accepted mid-turn, so a unit that has spent one of its two flags is
    // a state the rules distinguish. This is the difference §4.10 says a hash
    // without them could not see.
    {
        GameState a = initial;
        GameState b = initial;
        std::string e;
        markMoved(b.turn, 1, 0, e);
        check("GATE-REPLAY-FLAGS hasMoved-changes-the-digest",
              canonicalStateHash(a) != canonicalStateHash(b));
        GameState c = initial;
        markActed(c.turn, 1, 0, e);
        check("GATE-REPLAY-FLAGS hasActed-changes-the-digest",
              canonicalStateHash(a) != canonicalStateHash(c));
        check("GATE-REPLAY-FLAGS moved-and-acted-are-distinguishable",
              canonicalStateHash(b) != canonicalStateHash(c));
    }

    // ---- GATE-REPLAY-BUILD: the per-factory build record is hashed --------------
    {
        GameState a = initial;
        GameState b = initial;
        std::string e;
        markBuilt(b.turn, offsetToAxial(1, 1), 0, e);
        check("GATE-REPLAY-BUILD built-this-turn-changes-the-digest",
              canonicalStateHash(a) != canonicalStateHash(b));
    }

    // ---- T-SAVE-01 round-trip --------------------------------------------------
    // play N commands -> save -> load -> identical stateHash.
    {
        GameState played = initial;
        const ReplayResult r = replayLog(played, fullLog, tables);
        check("T-SAVE-01 (a) the log replays clean", r.ok && r.applied ==
              static_cast<int>(fullLog.size()));
        const std::string h1 = canonicalStateHash(played);

        const Save file = saveFor(fullLog, h1);
        const std::string text = serializeSave(file);
        Save parsed;
        const SaveLoadResult lr = loadSave(text, "roundtrip", expectationFor(file), parsed);
        check("T-SAVE-01 (b) the serialised save loads", lr.ok);

        GameState reloaded = initial;
        const ReplayResult r2 = replayLog(reloaded, parsed.commandLog, tables);
        check("T-SAVE-01 (c) the loaded log replays clean", r2.ok);
        const std::string h2 = canonicalStateHash(reloaded);
        check("T-SAVE-01 (d) save -> load -> identical stateHash", h1 == h2);
        check("T-SAVE-01 (e) the file's carried stateHash is the one it describes",
              parsed.stateHash == h2);
        check("T-SAVE-01 (f) the log survives the round trip entry for entry",
              parsed.commandLog.size() == fullLog.size());
    }

    // ---- T-SAVE-02 replay determinism ------------------------------------------
    // the same file loaded twice -> identical hashes. This composes T-HEX-07,
    // T-MOVE-06, T-FAME-09, T-TURN-09 and T-AI-06 end to end: the log's AI segment
    // was produced by row 6, and every tie-break inside the replay is theirs.
    {
        GameState seed = initial;
        replayLog(seed, fullLog, tables);
        const Save file = saveFor(fullLog, canonicalStateHash(seed));
        const std::string text = serializeSave(file);

        Save p1, p2;
        const SaveLoadResult l1 = loadSave(text, "twice-1", expectationFor(file), p1);
        const SaveLoadResult l2 = loadSave(text, "twice-2", expectationFor(file), p2);
        check("T-SAVE-02 (a) both loads succeed", l1.ok && l2.ok);

        GameState g1 = initial, g2 = initial;
        const ReplayResult r1 = replayLog(g1, p1.commandLog, tables);
        const ReplayResult r2 = replayLog(g2, p2.commandLog, tables);
        check("T-SAVE-02 (b) both replays succeed", r1.ok && r2.ok);
        check("T-SAVE-02 (c) the same file loaded twice -> identical hashes",
              canonicalStateHash(g1) == canonicalStateHash(g2));
        // and the byte stream, not only the digest: two digests can agree by
        // collision, two serialisations cannot agree by accident.
        check("T-SAVE-02 (d) identical canonical serialisation, not only digest",
              canonicalStateBytes(g1) == canonicalStateBytes(g2));
        // re-serialising the file reproduces it byte for byte
        check("T-SAVE-02 (e) serialize is stable across a round trip",
              serializeSave(p1) == serializeSave(p2));
    }

    // ---- T-SAVE-03 prefix validity ---------------------------------------------
    // every prefix of a valid log is itself a valid, LOADABLE save -- loadable
    // meaning replayable, which is the half part (a) could not assert.
    {
        bool allPrefixesLoad = true, allPrefixesAgree = true;
        for (std::size_t k = 0; k <= fullLog.size(); ++k) {
            const std::vector<SaveCommand> prefix(fullLog.begin(), fullLog.begin() +
                                                  static_cast<long>(k));
            GameState direct = initial;
            const ReplayResult rd = replayLog(direct, prefix, tables);
            if (!rd.ok) { allPrefixesLoad = false; break; }

            const Save file = saveFor(prefix, canonicalStateHash(direct));
            Save parsed;
            const SaveLoadResult lr = loadSave(serializeSave(file), "prefix",
                                               expectationFor(file), parsed);
            if (!lr.ok) { allPrefixesLoad = false; break; }

            GameState viaFile = initial;
            const ReplayResult rf = replayLog(viaFile, parsed.commandLog, tables);
            if (!rf.ok) { allPrefixesLoad = false; break; }
            if (canonicalStateHash(viaFile) != canonicalStateHash(direct))
                allPrefixesAgree = false;
        }
        check("T-SAVE-03 (a) every prefix is a loadable, replayable save",
              allPrefixesLoad);
        check("T-SAVE-03 (b) each prefix reaches the state replaying it directly does",
              allPrefixesAgree);
        check("T-SAVE-03 (c) the empty prefix is the initial state",
              fullLog.size() > 0);
    }

    // ---- T-SAVE-05 no partial load ---------------------------------------------
    // a log with an illegal command at index k is refused WHOLE; the pre-load state
    // survives. The tripwire the stub names is an implementation that applies then
    // validates, leaving a corrupted half-loaded state.
    {
        // An illegal command that is well FORMED -- part (a) would accept the file.
        // Moving a unit to a hex no route reaches is a rules refusal, not a parse one.
        //
        // THE INDEX MATTERS AND THE STARTING STATE MATTERS WITH IT. The illegal entry
        // sits at index 2, and the replay starts from the INITIAL state so that
        // indices 0 and 1 are legal and DO apply before the refusal. Started from a
        // state in which those two had already been played, entry 0 would be refused
        // as a repeat and nothing would be applied under any implementation -- so the
        // check would pass against an implementation that mutates in place, which is
        // the one defect it exists to catch. A partial-application check whose log
        // fails at index 0 asserts nothing.
        const std::size_t k = 2;
        std::vector<SaveCommand> bad = fullLog;
        bad.insert(bad.begin() + static_cast<long>(k),
                   cmd(SaveCommandKind::Move, 1, 0, 1, 4, 2, true, true));

        const GameState before = initial;
        const std::string hBefore = canonicalStateHash(before);
        const std::string bytesBefore = canonicalStateBytes(before);

        GameState target = before;
        const ReplayResult r = replayLog(target, bad, tables);
        check("T-SAVE-05 (a) the log is refused", !r.ok);
        check("T-SAVE-05 (b) the refusal names the offending index",
              r.failedIndex == static_cast<int>(k));
        check("T-SAVE-05 (c) it names T-SAVE-05 and gives a reason",
              r.failedId == "T-SAVE-05" && !r.reason.empty());
        check("T-SAVE-05 (d) nothing was applied", r.applied == 0);
        check("T-SAVE-05 (e) the pre-load state survives, by digest",
              canonicalStateHash(target) == hBefore);
        check("T-SAVE-05 (f) the pre-load state survives, field for field",
              canonicalStateBytes(target) == bytesBefore);

        // and the same for an illegal command at the LAST index -- a replayer that
        // validates the head and then trusts the tail passes (a)-(f) and fails here.
        std::vector<SaveCommand> tailBad = fullLog;
        tailBad.push_back(cmd(SaveCommandKind::Move, 1, 0, 99, 2, 1, true, true));
        GameState target2 = before;
        const ReplayResult r2 = replayLog(target2, tailBad, tables);
        check("T-SAVE-05 (g) an illegal command at the LAST index refuses the file",
              !r2.ok && canonicalStateBytes(target2) == bytesBefore);
    }

    // ---- GATE-REPLAY-FIXTURE: the committed parity fixture is not stale ---------
    // data/parity_fixture.save is the file T-INT-02 replays IN-ENGINE and compares
    // against §4.10's canonical state hash. It is COMMITTED BYTES, so it can go
    // stale the moment a rule, a table row or the scenario changes -- and a stale
    // fixture makes T-INT-02 compare the engine against a game that no longer
    // exists. This is the check that refuses to let that happen quietly.
    //
    // (d) IS THE ONE THAT CATCHES STALENESS. (b) and (c) are satisfied by any file
    // whose carried hash matches its own log, including one written before the rule
    // changed if the change happens not to move that log's final state. Only
    // re-emitting from the shipped inputs and comparing BYTES fails when the AI, the
    // seed, the tables or the scenario move.
    {
        std::vector<UnitDef>    sud;
        std::vector<TerrainDef> std_;
        Scenario                ssc;
        std::string             ferr;
        const bool loaded = loadShipped(dataDir, sud, std_, ssc, ferr);
        check("GATE-REPLAY-FIXTURE (a) the shipped tables and scenario load", loaded);

        std::string text;
        const std::string fixturePath = dataDir + "/parity_fixture.save";
        const bool read = readWholeFile(fixturePath, text);
        check("GATE-REPLAY-FIXTURE (b) the committed fixture is present", read);

        Save fx;
        const SaveLoadResult pr = read
            ? parseSave(text, "parity_fixture.save", fx)
            : SaveLoadResult();
        check("GATE-REPLAY-FIXTURE (c) it parses as a §4.10 save", pr.ok);

        RulesTables st;
        st.units = &sud;
        st.terrain = &std_;

        GameState sg;
        const bool seeded = loaded &&
            seedFromScenario(sg, ssc, st, kParityFirstSide, ferr);
        check("GATE-REPLAY-FIXTURE (d) the scenario seeds a GameState", seeded);

        const ReplayResult rr = (seeded && pr.ok)
            ? replayLog(sg, fx.commandLog, st)
            : ReplayResult();
        check("GATE-REPLAY-FIXTURE (e) its command log replays clean",
              rr.ok && rr.applied == static_cast<int>(fx.commandLog.size()));
        check("GATE-REPLAY-FIXTURE (f) the carried stateHash is the one it describes",
              rr.ok && canonicalStateHash(sg) == fx.stateHash);

        Save rebuilt;
        const bool rebuiltOk = loaded &&
            buildParityFixture(sud, std_, ssc, rebuilt, ferr);
        check("GATE-REPLAY-FIXTURE (g) re-emitting reproduces the committed bytes",
              rebuiltOk && read && serializeSave(rebuilt) == text);
    }

    // --- what did NOT run ------------------------------------------------------
    std::printf("\n");
    std::printf("NOT RUN  T-SAVE-06 stateHash stability across the headless and in-engine\n");
    std::printf("         builds. §4.11 marks it †, it is asserted JOINTLY with T-INT-02,\n");
    std::printf("         which replays IN-ENGINE -- so no headless build closes it, and\n");
    std::printf("         this one does not run the ID. It is NOT RUN here. The bridge\n");
    std::printf("         that landed at UE 0897cb5 replays data/parity_fixture.save\n");
    std::printf("         through the vendored modules and compares its own canonical\n");
    std::printf("         state hash against the one that file carries. What this build\n");
    std::printf("         supplies to that comparison is\n");
    std::printf("         its headless half -- the fixture and the hash it records --\n");
    std::printf("         and GATE-REPLAY-FIXTURE above is what keeps them fresh, so a\n");
    std::printf("         stale fixture cannot reach the in-engine side quietly.\n");
    std::printf("NOT RUN  T-SAVE-07 harness compatibility (a Balance Analyst self-play log\n");
    std::printf("         validates and replays as a save). cpp_reference/selfplay.cpp is a\n");
    std::printf("         combat-only 1v1 duel harness that prints a table and emits no\n");
    std::printf("         §4.10 command log, so this ID has no producer at any scope here.\n");
    std::printf("         Part (c), week 4.\n");
    std::printf("\n");
    std::printf("Row 10 is a PROPOSED ledger row (§4.11) and has none to flip. The four\n");
    std::printf("acceptance IDs this build closes are T-SAVE-01, T-SAVE-02, T-SAVE-03 and\n");
    std::printf("T-SAVE-05; T-SAVE-04 closed at part (a). GATE-REPLAY-* mint no acceptance\n");
    std::printf("ID, on the GATE-SAVE-PARSE / GATE-AI-SMOKE / GATE-CAP-PARTIAL precedent.\n");

    std::printf("\n%d/%d passed\n", g_total - g_fail, g_total);
    return g_fail == 0 ? 0 : 1;
}
